#!/bin/sh

set -e

case $1 in
        configure)

		if [ -e /var/www/html/ ] ; then 

			#Delete default directory for apache 2.4 
			rm -rf /var/www/html
		fi		

		if [ ! -L /var/www/srv ] ; then

			ln -s /usr/share/lliurex-www/srv /var/www/srv || true

		fi
		
		if [ ! -L /var/www/error ] ; then

			ln -s /usr/share/lliurex-www/error /var/www/error || true

		fi

		if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then

                        . /usr/share/apache2/apache2-maintscript-helper
                        apache2_invoke ensite error.conf
                fi
		
		invoke-rc.d apache2 reload || true
		;;
	*)
	        echo "[DEBUG] Unknow action ..."
	        ;;
		
esac
	
	
#DEBHELPER#

exit 0 		
