#!/bin/sh

set -e




case $1 in
	remove)

		rm -r /var/lib/lliurex-www/ || true

		if [ -L /var/www/srv ] ; then
	
			rm /var/www/srv || true

		fi

		if [ -L /var/www/error ] ; then

			rm /var/www/error
		fi
	;;

	failed-upgrade|upgrade|deconfigure)
	;;
esac

# Other Stuff #

#DEBHELPER#
	
exit 0 	
